export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT'
export const RESET = 'RESET'
export const CHECKOUT = 'CHECKOUT'

export const LOADORDERS = 'LOADORDERS'
export const ORDERLOADFAILED = 'ORDERLOADFAILED'

export const AUTHSUCCESS = 'AUTHSUCCESS'
export const AUTHFAIELD = 'AUTHFAIELD'
export const AUTHLOADING = 'AUTHLOADING'
export const AUTHLOGOUT = 'AUTHLOGOUT'
